title: OpenPMF
description: > # this means to ignore newlines until "show_excerpts:"
  사업 아이디어를 시장에서 빠르게 검증하세요! 1-2주 안에 빠른 시장 적합성 분석, 잠재 고객 발굴, 나아가 CRM 관리까지! OpenPMF 서비스로 사업과 시장, 고객을 매칭하세요!
baseurl: "/openPMF"
url: https://kimtaehyeong17.github.io/openPMF/ # change this URL, this is needed for generating right sitemap

permalink: "/blog/:title/"

plugins:
  - jekyll-feed
  - jekyll-soopr-seo-tag
  - jekyll-sitemap
  - jekyll-minifier

css_dir: "assets/css" # defaults to "css"

highlighter: rouge

collections:
  posts:
    output: true
    permalink: "/blog/:title"
  pages:
    output: true
    permalink: "/:title"

jekyll-minifier:
  uglifier_args:
    harmony: true

soopr:
  publish_token: "" # sign up at https://www.soopr.co to get your publish token and personalize share and reaction options

twitter:
  card: summary_large_image

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - package.json
  - package-lock.json
  - README.md
  - postcss.config.js
  - purgecss.config.js
  - tailwind.config.js
  - .gitignore
  - vendor
